---
# tasks file for rastandy.libreoffice-server

- name: Download LibreOffice
  get_url:
    url: "{{ libreoffice_donwload_url }}"
    dest: "{{ libreoffice_download_dir }}/{{ libreoffice_download_filename }}"
    checksum: "sha256:{{ libreoffice_sha256sum }}"

- name: Unarchive LibreOffice
  unarchive: 
    src: "{{ libreoffice_download_dir }}/{{ libreoffice_download_filename }}" 
    dest: "{{ libreoffice_download_dir }}"
    list_files: yes
    copy: no
  register: libreoffice_extracted

- name: Show extracted files
  debug: var=libreoffice_extracted
  when: debug

- name: Install extracted rpm packages
  shell: /bin/yum -y localinstall {{ libreoffice_download_dir }}/{{ libreoffice_extracted.files[0] }}RPMS/*
  args:
    creates: "{{ libreoffice_install_dir }}"
