---
# tasks file for rastandy.libreoffice-server

- name: Install LibreOffice headless
  yum: name=libreoffice-headless state=present

- name: Create LibreOffice user
  group: name="{{ libreoffice_group }}"

- name: Create LibreOffice user
  user: name="{{ libreoffice_user }}" group="{{ libreoffice_group }}"

- name: Create libreoffice service
  template: src="service_systemd.j2" dest=/etc/systemd/system/libreoffice-server.service owner=root group=root mode=0644
  when:
    - ansible_local.util.init.system is defined
    - ansible_local.util.init.system == 'systemd'

- name: Enable LibreOffice service
  service: name=libreoffice-server state=started enabled=yes
